name: Give a name

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    

jobs:
  test_django:
    runs-on: ubuntu-latest
    env:
       DJANGO_SECRET_KEY: "this-is-it"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run hello world
        run: |
            echo "${{ env.DJANGO_SECRET_KEY }}"
           