name: Give a name

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    

jobs:
  test_django:
    runs-on: ubuntu-latest
    env:
       DJANGO_SECRET_KEY: "${{ secrets.DJANGO_SECRET_KEY }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run hello world
        run: |
            echo "${{ env.DJANGO_SECRET_KEY }}"
      
      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
           python-version: "3.10"
      - name: Install requirements
        run: |
          pip3 install -r requirements.txt
      - name: Run Tests
        run: |
          python3.10 manage.py test
           