name: Give a name

on:
  workflow_dispatch:
    

jobs:
  test_django:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run hello world
        run: |
            echo "hello world"
            echo "hello world"
            echo "hello world"
